Revert renovate/openstack-k8s-operators PR 132
This reverts commit 81e4f6d1e050203746a96be10e80f5cca461f7c9, which
introduced a build error:

../deps/gomod/pkg/mod/k8s.io/kube-openapi@\
  v0.0.0-20230308215209-15aac26d736a/pkg/cached/cache.go\
  :242:16:undefined: atomic.Pointer